sentimente_list = [
    {"nume": "fericire", "nev": "boldogság", "mood": "pozitiv"},
    {"nume": "veselie", "nev": "vidámság", "mood": "pozitiv"},
    {"nume": "bucurie", "nev": "öröm", "mood": "pozitiv"},
    {"nume": "dragoste", "nev": "szerelem, szeretet", "mood": "pozitiv"},
    {"nume": "dor", "nev": "vágy"},
    {"nume": "dorință", "nev": "vágyakozás"},
    {"nume": "tristețe", "nev": "szomorúság", "mood": "negativ"},
    {"nume": "părere de rău", "nev": "sajnálat", "mood": "negativ"},
    {"nume": "durere sufletească", "nev": "lelki fájdalom", "mood": "negativ"},
    {"nume": "suferință", "nev": "szenvedés", "mood": "negativ"},
    {"nume": "melancolie", "nev": "melankólia"},
    {"nume": "nostalgie", "nev": "nosztalgia"},
    {"nume": "depresie", "nev": "depresszió", "mood": "negativ"},
    {"nume": "spaimă existențială", "nev": "létfélelem", "mood": "negativ"},
    {"nume": "supărare", "nev": "harag", "mood": "negativ"},
    {"nume": "jale", "nev": "gyász", "sinonim":"doliu", "mood": "negativ"},
    {"nume": "singurătate", "nev": "magány", "mood": "negativ"},
    {"nume": "pasiune", "nev": "szenvedély", "mood": "pozitiv"},
    {"nume": "ură", "nev": "gyűlölet", "mood": "negativ"},
    {"nume": "gelozie", "nev": "irigység", "mood": "negativ"},
]
