teme_list = [
    {"nume": "natură", "nev": "természet"},
    {"nume": "viață omului", "nev": "emberi élet"},
    {"nume": "naștere", "nev": "születés"},
    {"nume": "iubire", "nev": "szerelem, szeretet"},
    {"nume": "educație", "nev": "nevelés"},
    {"nume": "bătrânețe", "nev": "öregkor"},
    {"nume": "moarte", "nev": "halál"},
    {"nume": "destin uman", "sinonim": "soartă omului", "nev": "emberi sors"},
    {"nume": "religie", "nev": "vallás"},
    {"nume": "credință", "nev": "hit"},
    {"nume": "artă", "nev": "művészet"},
    {"nume": "cultură", "nev": "kultúra"},
    {"nume": "timp", "nev": "idő"},
    {"nume": "patrie", "nev": "haza"},
    {"nume": "creație artistică", "nev": "művészi alkotás"},
    {"nume": "avere", "nev": "vagyon"},
    {"nume": "moștenire", "nev": "örökség"},
    {"nume": "viața socială", "nev": "közösségi élet"},
    # {"nume": "+sentimente eului liric", "nev": "+lírai én érzelmei"},
]